### ISSUE TITLE
License missing...

### ISSUE THREAD

**Issue by mirchiseth** [Crizstian/cinema-microservice#3]
Hello Crizstian,

Thanks for putting this here. I wanted to use these tutorials and modify them to deploy on CloudFoundry instead of Docker. But there is no license mentioned any where and I hesitate to use it without seeing a license. Would be great if you can include something like AGPLv2 or MIT.

Keep up the good work.

**Comment by Crizstian** [comment]
Thanks for the observation MIT License has been added.

**Comment by mirchiseth** [comment]
Thanks Crizstian
